### PR TITLE
Added ShortFrame UserMod

### PR DESCRIPTION
**Pull request by BlackShadeOSS**
Modified left and right part of the frame so less Z space is used.

### CODE REVIEW

**Comment by TheSin-** [comment]
A change to the LEFT and RIGHT for Blackbird was just added, did you want to fix them before I accept this?

Also please add in the README "Support for these are not handled by the StealthChanger Team, and all docks must use the same height, DO NOT MIX AND MATCH"

**Comment by BlackShadeOSS** [comment]
Yes sure I will fix it soon.

**Comment by BlackShadeOSS** [comment]
Fix coming this week

**Comment by BlackShadeOSS** [comment]
I updated ShortFrame please if you can merge it in.

**Comment by TheSin-** [comment]
Add a note to readme that if used you can only use short and that sb won’t work at all and I’ll accept it

**Comment by BlackShadeOSS** [comment]
Sb will work

**Comment by BlackShadeOSS** [comment]
But more info about SB with short frame soon

**Comment by TheSin-** [comment]
Currently it barely does as it’ll hit the front extrusion if using a cross bar, so no it won’t even if you wish really hard and we have to support it so put the note in

**Comment by BlackShadeOSS** [comment]
Better?

**Comment by TheSin-** [comment]
it's not actually, it's more confusing.

Also a note about not being compatible with Frame Buffer.

**Pull request merged**
