### PR TITLE
Improve BOM readability

### PR DESCRIPTION
**Pull request by onsimon**

### CODE REVIEW

**Comment by TheSin-** [comment]
Since I can't view it what does the double space do? new line in MarkDown?  Cause if so that seems like it'll be really really spaced specially on a phone size display.

**Comment by onsimon** [comment]
@TheSin- correct, they enable soft/single line break because the current version renders the markdown items on a single line

Preview the PR file here: https://github.com/hellbe/ModularDock/blob/patch-1/BOM.md

**Comment by onsimon** [comment]
Current without trailing spaces:
image

With trailing spaces in PR:
image

**Comment by TheSin-** [comment]
wow that must be a browser issue cause that's not how mine is at all, list items auto get a line feed.

Screenshot 2024-06-28 at 8 02 40 AM

I'd check your browser as I test with all 3 majors and mobile and I don't see this issue at all.

I'm going to accept it but if it adds double lines I'll be reverting it right away.

**Comment by TheSin-** [comment]
I was looking at the wrong BOM, I see now, I'm going to fix it properly, it should be a list and somehow that got missed.

**Comment by onsimon** [comment]
@TheSin- cool, you can also do markdown check boxes with `- [ ] item`. Might be a nice touch :)

- [x] 4x6 M3 BHCS
- [x] 1x40 M3 BHCS

**Comment by onsimon** [comment]
> wow that must be a browser issue cause that's not how mine is at all, list items auto get a line feed.

It is markdown standard: https://www.markdownguide.org/basic-syntax/#line-breaks

**Pull request merged**
